name: CI/CD for mern-stack

on: [push]

jobs:
    # Build Job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install Frontend Dependencies
              working-directory: ./frontend
              run: npm install

            - name: Build Frontend
              working-directory: ./frontend
              run: npm run build

            - name: Install Backend Dependencies
              run: |
                  npm install

            - name: Build Both Projects
              run: |
                  npm run build

            - name: Upload artifact to enable deployment
              uses: actions/upload-artifact@v3
              with:
                  name: poduction file
                  path: ./dist

    # Deploy Job
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v3
              with:
                  name: poduction file
                  path: ./dist

            - name: Deploy Frontend
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_dir: ./dist/frontend

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_dir: ./dist/backend
